// 錯誤碼定義

export enum ErrorCode {
  // File errors
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_FORMAT_UNSUPPORTED = 'FILE_FORMAT_UNSUPPORTED',
  FILE_READ_FAILED = 'FILE_READ_FAILED',

  // Conversion errors
  CONVERSION_FAILED = 'CONVERSION_FAILED',
  FFMPEG_NOT_FOUND = 'FFMPEG_NOT_FOUND',

  // Download errors
  DOWNLOAD_FAILED = 'DOWNLOAD_FAILED',
  YTDLP_PATH_READ_FAILED = 'YTDLP_PATH_READ_FAILED',

  // Transcription errors
  TRANSCRIPTION_FAILED = 'TRANSCRIPTION_FAILED',
  WHISPER_CLI_NOT_FOUND = 'WHISPER_CLI_NOT_FOUND',

  // Validation errors
  INVALID_LOCALE = 'INVALID_LOCALE',
  INVALID_OUTPUT_FORMAT = 'INVALID_OUTPUT_FORMAT',
  INVALID_SETTING_VALUE = 'INVALID_SETTING_VALUE'
}
