export const IPC_CHANNELS = {
  WHISPER_START: 'whisper:start',
  WHISPER_PROGRESS: 'whisper:progress',
  WHISPER_COMPLETE: 'whisper:complete',
  WHISPER_ERROR: 'whisper:error',
  MODEL_LIST: 'model:list',
  MODEL_DOWNLOAD: 'model:download',
  MODEL_PROGRESS: 'model:progress',
  MODEL_OPEN_FOLDER: 'model:open-folder',
  AUDIO_CONVERT: 'audio:convert',
  AUDIO_PROGRESS: 'audio:progress',
  OUTPUT_FORMAT: 'output:format',
  OUTPUT_GET_FORMATS: 'output:getFormats',
  AI_RUN: 'ai:run',
  AI_PROGRESS: 'ai:progress',
  AI_RESULT: 'ai:result',
  AI_ERROR: 'ai:error',
  AI_STOP: 'ai:stop',
  AI_GET_STATUS: 'ai:getStatus',
  AI_LIST_MODELS: 'ai:listModels',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_OPEN_OUTPUT_FOLDER: 'settings:open-output-folder',
  YTDLP_DOWNLOAD: 'ytdlp:download',
  YTDLP_CANCEL: 'ytdlp:cancel',
  YTDLP_PROGRESS: 'ytdlp:progress',
  YTDLP_COMPLETE: 'ytdlp:complete',
  YTDLP_ERROR: 'ytdlp:error'
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]
